[default]
extend-ignore-re = [
  # disable spellcheck for specific lines with trailing `// spellchecker:disable-line`
  "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
  # links to commits in changelogs and other markdown
  "\\[[0-9a-fA-F]{7,}\\]\\([0-9a-fA-F]{40,}\\)",
]
ignore-hex = true

[default.extend-words]
# keep-sorted start
Ines = "Ines"
Linz = "Linz"
Thay = "Thay"
flate = "flate"
lits = "lits"
# keep-sorted end

[files]
extend-exclude = [
  "data/**",
  "cadical/cppsrc/**",
  "cadical/patches/**",
  "glucose/cppsrc/**",
  "kissat/csrc/**",
  "minisat/cppsrc/**",
]
