name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo check
        run: cargo check --workspace --verbose --features=all
          
  test:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build project
        run: cargo build
      - name: Run cargo test suite
        run: cargo test --workspace --verbose

  pystubs:
    name: Test python stubs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install maturin from PyPI
        uses: install-pinned/maturin@dfebcaa782a69944b584ec164e97fbbd09885352
      - name: Install mypy from PyPI
        uses: install-pinned/mypy@c2223951641cbb406fa8526d08f0690899f130e4
      - name: Install python project
        run: maturin build -m rustsat/Cargo.toml && pip install --no-index --find-links target/wheels/ rustsat
      - name: Test stubs
        run: stubtest --mypy-config-file rustsat/pyproject.toml --allowlist rustsat/stubtest-allowlist.txt rustsat
